### ISSUE TITLE
Different "from oscaar import differentialPhotometry returned non-zero exit status:" Problem

### ISSUE THREAD

**Issue by tamorris** [OSCAAR/OSCAAR#170]
Doing some work with OSCAAR after a hiatus. I've been trying to run this data on WASP 104-b, but have been getting this error. I've tried most of the common issues I remember, and am now going through my data set frame-by-frame to see if there are any bad images the code might be having issue with (though it looks pretty good so far). The progress bar fills 100% before the error comes, making me think that it may be a small issue. The last line of the error is the same as in the latest issue listed, but the rest seems different to me. Any help that could be provided on this issue (from @bmorris3 or any other team members) is greatly appreciated.

It's maybe worth mentioning that the computer I'm running this on has a copied hard drive from an older one we've used. As far as I know, all the needed dependencies should be on the machine, but would this message come up if the new setup couldn't access a function it needs, etc?

![error_2015](https://cloud.githubusercontent.com/assets/5004000/7261247/d042a5de-e835-11e4-8679-e958e53c16cc.JPG)

**Comment by bmorris3** [comment]
Hi Taylor! My first impression is that this looks like a regions file error. Do you have at least one target and one comparison star in the regions file?

**Comment by tamorris** [comment]
I did, but this gives me something to try. I will try making a new regions file and report back.

Thanks,

**Comment by bmorris3** [comment]
Feel free to copy and paste your regions file into a comment, too.

**Comment by tamorris** [comment]
You were correct about it being a region file issue. I was going to file -> save as, then putting in ".reg" as the file type instead of going to region -> save regions, and saving that way. That matters. Now it's generating curves (albeit very poor ones, but this is likely a data issue). Thanks for your help! If more questions come up over the next couple of days, I'll be sure to post. I was planning on doing MCMC after getting good curves, but I don't know if that'll be doable with this data set.

**Comment by bmorris3** [comment]
No problem. Keep in touch about that – I'm thinking about replacing the fitting module with a much more robust one.
