### ISSUE TITLE
Trying to Setup/Install Oscaar

### ISSUE THREAD

**Issue by jessiehs** [OSCAAR/OSCAAR#172]
I am having a problem setting Oscaar up.  For some reason it says I am not connected to the internet, but I am.  I would really love some help.  
![screenshot 1](https://cloud.githubusercontent.com/assets/12161342/7382529/105c7d54-edde-11e4-861c-2206935f7c56.png)

**Comment by bmorris3** [comment]
I'm not sure if this is the problem, but when you set the path as per the [installation instructions](https://github.com/OSCAAR/OSCAAR/blob/master/INSTALL.txt), use the following command including the word set: 
```
set path=%path%;C:\python27
```

**Comment by jessiehs** [comment]
Nope.  :(

**Comment by jessiehs** [comment]
It still says the same thing about the internet.

**Comment by bmorris3** [comment]
Interesting. Which OS and version of Python are you running?

**Comment by bmorris3** [comment]
Sorry about that – our little DNS bypass trick was outdated. I've updated the code, it shouldn't fail for that reason anymore. Try downloading OSCAAR again and reinstalling.
