### ISSUE TITLE
Numpy not found

### ISSUE THREAD

**Issue by jessiehs** [OSCAAR/OSCAAR#173]
I still cannot install OSCAAR.  :(
![screenshot 2](https://cloud.githubusercontent.com/assets/12161342/7463268/16387104-f286-11e4-9d3a-603342eb5441.png)

**Comment by bmorris3** [comment]
Have you installed all of the [required dependencies](https://github.com/OSCAAR/OSCAAR/wiki/Dependencies)?

**Comment by jessiehs** [comment]
I tried reinstalling NumPy, but it didn't help.

**Comment by bmorris3** [comment]
Are you still seeing the same error?

**Comment by jessiehs** [comment]
Yes

**Comment by bmorris3** [comment]
What happens when you execute: 

```
python -c "import numpy; print(numpy.__version__)"
```

**Comment by jessiehs** [comment]
![screenshot 4](https://cloud.githubusercontent.com/assets/12161342/7922653/aefcb660-087b-11e5-854e-976e5516629e.png)

**Comment by bmorris3** [comment]
You do not have numpy installed.
