### ISSUE TITLE
RunTimeError: Numpy not found

### ISSUE THREAD

**Issue by StarManFlorida** [OSCAAR/OSCAAR#177]
Really new at this - OSCAAR - and just started downloading and installing, but ended with the error in my "subject line."
I have no idea what caused this and not idea where to go from here.

Frank M.

**Comment by StarManFlorida** [comment]
Close this question.  I located the answer...

**Comment by tanishakasar** [comment]
Hi, I'm currently facing the same problem, I would appreciate if you could share how you solved this problem.
Thanks!
